#!/usr/bin/env php

<?php

/**
 * Timino Console (CLI) Tool for Timino MVC Framework
 * 
 * @package     Timino
 * @author      Lotfio Lakehal <lotfiolakehal@gmail.com>
 * @copyright   2018 Lotfio Lakehal
 * @license     MIT
 * @link        https://github.com/lotfio-lakehal/console
 *
 * This program is free software: you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundat- ion, either version 
 * 3 of the License, or (at your option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty 
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 * 
 */


/**
 * require autoload file
 */

require "vendor/autoload.php";



// use
use Console\Core\{Input, Output, App, Builder};

// input object
$inp = new Input;

// output object
$out = new Output;

// builder object
$builder = new Builder;

// instantiate application
$app = new App($inp, $out, $builder);

// run application
$app->run();



