<?php

/**
 * Timino - PHP MVC framework
 *
 * @package     Timino
 * @author      Lotfio Lakehal <contact@lotfio-lakehal.com>
 * @copyright   2017 Lotfio Lakehal
 * @license     MIT
 * @link        https://github.com/lotfio-lakehal/timino
 *
 * Copyright (C) 2018
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * INFO :
 * login Model class
 *
 * Generated by timinocli at 2017-11-07 14:47:36
 */

namespace App\Models;

use App\Core\Model;

class Auth extends Model
{
    /**
     * login businness logic
     *
     * @return array
     */
    public function logUser()
    {
        if($this->form->post('login'))
        {
            $errors = [];

            $email = $this->validate->email($_POST['u_email']) OR $errors[] = 'Please Enter a correct email !';
            $pass  = $this->validate->string($_POST['u_pass']) OR $errors[] = 'Please Enter a correct password !';
            $token = $this->validate->string($_POST['CSRF'])   OR $errors[] = 'CSRF token is wrong !';
            if($token != $this->session->get('CSRF')) $errors[] = 'Security Error CSRF protection !';

            if(empty($errors))
            {
               $check = $this->record->select->from('Users','*', array(
                    "Email | =" => $email
                ));

               if($check) // if email exists
               {
                   if($this->token->verifyPasswd($pass, $check[0]->Passwd)) // if password match
                   {
                       $this->session->regenerate();
                       $this->session->set("Email", $email);
                       $this->redirect->to('/welcome');
                   }

                   return ["Error Wrong Email or Password"];
               }

                // if error email or password
                return ["Error Wrong Email or Password"];
            }

            // if not empty errors
            return $errors;
        }
    }

    /**
     * register businness logic
     *
     * @return array|bool
     */
    public function registerUser()
    {
        if($this->form->post('register'))
        {
            $errors = [];

            $email  = $this->validate->email($_POST['u_email'])  OR $errors[]  = 'Please Enter a correct email address !';
            $pass   = $this->validate->string($_POST['u_pass'])  OR $errors[]  = 'Please Enter a correct password !';
            $cpass  = $this->validate->string($_POST['uc_pass']) OR $errors[]  = 'Please Enter a confirmation correct password !';

            if($pass !== $cpass) $errors[] = 'Error Password mis match !';

            $gender = $this->validate->string($_POST['gender'], 1) OR $errors[]  = 'Please select your gender!';

            $token = $this->validate->string($_POST['CSRF'])   OR $errors[]   = 'CSRF token is wrong !';
            if($token != $this->session->get('CSRF')) $errors[] = 'Security Error CSRF protection !';

            if(empty($errors))
            {
                $insert = $this->record->insert->into('Users', array(
                    "Email"  => $email,
                    "Passwd" => $this->token->hashPasswd($pass),
                    "Gender" => $gender
                ));

                if($insert) return true;


                // if error email or password
                return ["Error during registration !"];
            }

            // if not empty errors
            return $errors;
        }
    }

    /**
     * log out method
     */
    public function logOutUser()
    {
        $this->session->destroy();
        $this->redirect->to('/');
    }
}